---
- name: dnsmasq_config | Configuring DNSMasq Default Settings
  template:
    src: etc/default/dnsmasq.j2
    dest: /etc/default/dnsmasq
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart dnsmasq
  become: true
  when: ansible_os_family == "Debian"

- name: dnsmasq_config | Configuring DNSMasq
  template:
    src: etc/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
  become: true

- name: dnsmasq_config | Ensuring {{ dnsmasq_tftpboot_dir }} Exists
  file:
    path: "{{ dnsmasq_tftpboot_dir }}"
    state: directory
  become: true
  when: >
    dnsmasq_enable_tftp is defined and
    dnsmasq_enable_tftp
