---
- name: debian | Installing DNSMasq
  apt:
    name: dnsmasq
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Ensuring DNSMasq Service Is Enabled And Started
  service:
    name: dnsmasq
    enabled: true
    state: started
  become: true
