---
# tasks file for ansible-dnsmasq
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: opensuse.yml
  when: ansible_os_family == "openSUSE Leap"

- include: config_dnsmasq.yml
  tags:
    - config_dnsmasq
  when: config_dnsmasq
