---
- name: opensuse | Installing DNSMasq
  zypper:
    name: "dnsmasq"
    state: "present"

- name: opensuse | Ensuring DNSMasq Service Is Enabled and Started
  service:
    name: "dnsmasq"
    state: "started"
    enabled: yes
