---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      exclude: molecule
platforms:
  - name: centos6
    image: centos:6
    privileged: true
  - name: centos7
    image: centos:7
    command: /sbin/init
    privileged: true
    capabilities:
      - NET_ADMIN
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian9
    image: debian:9
    privileged: true
  - name: debian10
    image: debian:10
    privileged: true
  - name: ubuntu1404
    image: ubuntu:14.04
    privileged: true
  - name: ubuntu1604
    image: ubuntu:16.04
    privileged: true
  - name: ubuntu1804
    image: ubuntu:18.04
    privileged: true
  - name: ubuntu1904
    image: ubuntu:19.04
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["303", "503"]
verifier:
  name: testinfra
  lint:
    name: flake8
